# Generated by Django 2.1.2 on 2019-09-28 19:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('valor', models.FloatField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.AccountModel')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transactions', models.CharField(max_length=30)),
                ('valor', models.FloatField()),
                ('contaDestino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='api.AccountModel')),
                ('contaOrigin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destiny', to='api.AccountModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, null=True, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('bairro', models.CharField(max_length=150, null=True)),
                ('complemento', models.CharField(max_length=150, null=True)),
                ('dataNascimento', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('pais', models.CharField(max_length=100, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=150)),
                ('rua', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserModel'),
        ),
    ]
