# Generated by Django 2.2.5 on 2019-09-28 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.IntegerField()),
                ('saldo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(default='-- -- --', max_length=300)),
                ('city', models.CharField(max_length=120, null=True)),
                ('district', models.CharField(max_length=150, null=True)),
                ('complement', models.CharField(max_length=150, null=True)),
                ('date_of_birth', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100, null=True)),
                ('number', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transactions', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('account_destiny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destiny', to='api.AccountModel')),
                ('account_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='api.AccountModel')),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserModel'),
        ),
    ]
