# Generated by Django 2.2.5 on 2019-09-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='account_origin',
            new_name='contaDestino',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='value',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='complement',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='country',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='district',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='date_of_birth',
            new_name='dataNascimento',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='first_name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='number',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='street',
            new_name='rua',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='last_name',
            new_name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='account_destiny',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='token',
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='contaOrigin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destiny', to='api.AccountModel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
