# Generated by Django 2.2.5 on 2019-09-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='TransactionModel',
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='contaDestino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='api.AccountModel'),
        ),
        migrations.AddField(
            model_name='transfermodel',
            name='contaOrigin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destiny', to='api.AccountModel'),
        ),
    ]
